package httpapi

import (
	"log/slog"
	"net/http"
	"time"

	"yujian.me/server/internal/auth"
)

// LoggingMiddleware emits one structured event per request without recording
// headers or bodies. The request ID is generated by the outer middleware and
// the actor subject is read from the private authentication context.
func LoggingMiddleware(next http.Handler, logger *slog.Logger) http.Handler {
	if logger == nil {
		logger = slog.Default()
	}
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		started := time.Now()
		response := &statusWriter{ResponseWriter: writer}
		next.ServeHTTP(response, request)
		actorSubject := ""
		if principal, ok := auth.PrincipalFromContext(request.Context()); ok {
			actorSubject = principal.Subject
		}
		logger.Info("http request",
			"request_id", request.Header.Get("X-Request-ID"),
			"actor_subject", actorSubject,
			"route", request.URL.Path,
			"status", response.statusCode(),
			"duration_ms", time.Since(started).Milliseconds(),
		)
	})
}

type statusWriter struct {
	http.ResponseWriter
	wroteHeader bool
	status      int
}

func (writer *statusWriter) WriteHeader(status int) {
	if writer.wroteHeader {
		return
	}
	writer.wroteHeader = true
	writer.status = status
	writer.ResponseWriter.WriteHeader(status)
}

func (writer *statusWriter) Write(value []byte) (int, error) {
	if !writer.wroteHeader {
		writer.WriteHeader(http.StatusOK)
	}
	return writer.ResponseWriter.Write(value)
}

func (writer *statusWriter) statusCode() int {
	if writer.status == 0 {
		return http.StatusOK
	}
	return writer.status
}
